In [1]:
import numpy as np


In [2]:
sales_list=[120,150,300,250,90]
sales_array=np.array(sales_list)
print(sales_array)

[120 150 300 250  90]


In [3]:
#Features:[Age,income_in_k,credit_score]
customer_matrix=np.array([
    [25,50,710],
    [41,95,780],
    [32,65,620]
])
print(customer_matrix)

[[ 25  50 710]
 [ 41  95 780]
 [ 32  65 620]]


In [4]:
#generating data placeholders automatically
zero_matrix=np.zeros((3,4)) #a matrix of 3 rows and 4 columns with filled with 0
sequenced_array=np.arange(0,10,2) 
print("Sales array:", sales_array)
print("\nCustomer matrix shape: ", customer_matrix.shape)
print("\nSequenced array: ", sequenced_array)
print(zero_matrix)

Sales array: [120 150 300 250  90]

Customer matrix shape:  (3, 3)

Sequenced array:  [0 2 4 6 8]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
#Slicing
traffic=np.array([500,123,545,605,780,2200])


In [6]:
weekend_traffic=traffic[-2:]
print(weekend_traffic)

[ 780 2200]


In [7]:
sensors=np.array([
    [12.1,14.3,15.2],
    [10.5,11.2,12.6],
    [14.1,16.4,18.3],
    [18.9,19.1,20.3]
])


In [8]:
specific_reading=sensors[2,1]
print(specific_reading)

16.4


In [9]:
top_sensors=sensors[0:2,:]
print(top_sensors)

[[12.1 14.3 15.2]
 [10.5 11.2 12.6]]


In [10]:
final_readings=sensors[:, 2]
print(final_readings)

[15.2 12.6 18.3 20.3]


In [11]:
#Reshaping
flat_temps=np.array([22,24,25,23,27,24,23,22,25,26,24,25])
structured_temps=flat_temps.reshape(4,3)
print(structured_temps)

[[22 24 25]
 [23 27 24]
 [23 22 25]
 [26 24 25]]


In [12]:
fahrenheit_temps=(structured_temps*9/5)+32
print("\nTemperatures in Fahrenheit:\n", fahrenheit_temps)


Temperatures in Fahrenheit:
 [[71.6 75.2 77. ]
 [73.4 80.6 75.2]
 [73.4 71.6 77. ]
 [78.8 75.2 77. ]]


In [13]:
scores=np.array([
    [85,90,78,92],
    [70,80,75,85],
    [85,92,88,96]
])
print("Overall highest score in the class:",np.max(scores))
print("Overall average score:",round(np.mean(scores)))

Overall highest score in the class: 96
Overall average score: 85


In [14]:
subject_averages=np.mean(scores,axis=0).round(2)
print("Average score for each subjects:",subject_averages)

Average score for each subjects: [80.   87.33 80.33 91.  ]


In [15]:
student_avereges=np.mean(scores,axis=1)

In [16]:

import time
size=1_000_000
python_list=list(range(size))
numpy_array=np.arange(size)

In [17]:
start_time=time.time()
python_list_result=[x*2 for x in python_list]
python_duration=time.time()-start_time

In [18]:
start_time=time.time()
numpy_array_result=numpy_array*2
numpy_duration=time.time()-start_time
print(f"Time taken by standard Python list:{python_duration:.5f} seconds")
print(f"Time taken by numpy python list: {numpy_duration:.5f} seconds")
print(f"Numpy is roughly {round(python_duration/numpy_duration)}x faster")


Time taken by standard Python list:0.06794 seconds
Time taken by numpy python list: 0.00370 seconds
Numpy is roughly 18x faster
